version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: loja_db
      MYSQL_USER: loja_user
      MYSQL_PASSWORD: 123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net

volumes:
  mysql_data:

networks:
  backend-net:
